### PR TITLE
Fixing some mistakes

### PR DESCRIPTION
**Pull request by DasLixou**

### CODE REVIEW

**Comment by LunaeSomnia** [comment]
Hey! Thanks for opening the first PR here.

However, the website doesn't accept PRs yet, specially in the documentation/tutorial/blog part of it. Currently it's full of placeholders and a really really old and un-updated version of the vizia book granted by @geom3trik.

I'm merging your PR, although it's kind of in vain... the vizia book is in the process of a complete overhaul 😅 

I'm updating the `README.md` file so this confusion (hopefully) doesn't happen again. I don't want to waste people's time 😄

**Comment by DasLixou** [comment]
Oh! And i thougth the book was a deleted repo and that all docs are now here 🤣

**Comment by LunaeSomnia** [comment]
I have some ideas about it. We could update the book independently and the site could just fetch from there. This would avoid duplication and allow independent changes without rebuilding the website every time.
This, however, means that some metadata needs to be stored in the docs repo for it to be usable by the website

**Comment by DasLixou** [comment]
> I have some ideas about it. We could update the book independently and the site could just fetch from there. This would avoid duplication and allow independent changes without rebuilding the website every time.
> This, however, means that some metadata needs to be stored in the docs repo for it to be usable by the website

I thought that was the idea all the time? 😅

**Pull request merged**
